version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    container_name: db-nextcloud
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /compose-projects/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pC3Ezwcakn2bcFenDuzCeDhfAj3aC9whACfqyytn34
      - MYSQL_PASSWORD=o7jDjkshigykg54go7AbrhovsbhAgzny2zvnxAosfg
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    ports:
      - 9999:80
    links:
      - db
    volumes:
      - /compose-projects/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=o7jDjkshigykg54go7AbrhovsbhAgzny2zvnxAosfg
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - OVERWRITEHOST=cloud.fetox.de
